In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data_frame = pd.read_csv('Entrenamieto_ECI_2020.csv')
data_frame.Account_Created_Date = pd.to_datetime(data_frame.Account_Created_Date)
data_frame.Actual_Delivery_Date = pd.to_datetime(data_frame.Actual_Delivery_Date)
data_frame.Opportunity_Created_Date = pd.to_datetime(data_frame.Opportunity_Created_Date)
data_frame.Quote_Expiry_Date = pd.to_datetime(data_frame.Quote_Expiry_Date)
data_frame.Last_Modified_Date = pd.to_datetime(data_frame.Last_Modified_Date)
data_frame.Planned_Delivery_Start_Date = pd.to_datetime(data_frame.Planned_Delivery_Start_Date)
data_frame

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,...,Delivery_Quarter,Delivery_Year,Actual_Delivery_Date,TRF,Total_Amount_Currency,Total_Amount,Total_Taxable_Amount_Currency,Total_Taxable_Amount,Stage,Prod_Category_A
0,27761,EMEA,None,1,1,1,1,0,Bureaucratic_Code_4,2015-06-16,...,Q2,2016,NaT,10,EUR,5272800.00,EUR,5272800.0,Closed Lost,Prod_Category_A_None
1,27760,EMEA,None,0,0,0,0,0,Bureaucratic_Code_4,2015-06-16,...,Q1,2016,NaT,0,EUR,48230.00,EUR,48230.0,Closed Won,Prod_Category_A_None
2,27446,Americas,NW America,0,0,0,0,0,Bureaucratic_Code_4,2015-04-21,...,Q1,2016,NaT,0,USD,83865.60,USD,83865.6,Closed Won,Prod_Category_A_None
3,16808,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,Q1,2018,NaT,14,USD,7421881.50,USD,7421881.5,Closed Lost,Prod_Category_A_None
4,16805,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,Q1,2018,NaT,25,USD,13357192.50,USD,13357192.5,Closed Lost,Prod_Category_A_None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16942,8781,EMEA,Austria,1,1,1,1,0,Bureaucratic_Code_4,2016-01-15,...,Q1,2016,NaT,0,EUR,103350.00,EUR,299715.0,Closed Won,Prod_Category_A_None
16943,8786,EMEA,Austria,1,1,1,1,0,Bureaucratic_Code_4,2016-01-15,...,Q2,2016,NaT,0,EUR,93015.00,EUR,299715.0,Closed Won,Prod_Category_A_None
16944,8792,EMEA,Austria,1,1,1,1,0,Bureaucratic_Code_4,2016-01-15,...,Q1,2016,NaT,0,EUR,103350.00,EUR,299715.0,Closed Won,Prod_Category_A_None
16945,28561,Americas,NE America,1,1,1,1,0,Bureaucratic_Code_4,2015-10-20,...,Q2,2016,NaT,4,USD,2346796.88,USD,0.0,Closed Lost,Prod_Category_A_None
16946,28318,Americas,NE America,1,1,1,1,0,Bureaucratic_Code_4,2015-09-03,...,Q3,2016,NaT,40,USD,25603200.00,USD,0.0,Closed Lost,Prod_Category_A_None

In [4]:
oportunidades_perdidas_Americas = data_frame[(data_frame.Stage == 'Closed Lost') & (data_frame.Region == 'Americas')]
oportunidades_perdidas_Americas

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,...,Delivery_Quarter,Delivery_Year,Actual_Delivery_Date,TRF,Total_Amount_Currency,Total_Amount,Total_Taxable_Amount_Currency,Total_Taxable_Amount,Stage,Prod_Category_A
3,16808,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,Q1,2018,NaT,14,USD,7421881.50,USD,7421881.5,Closed Lost,Prod_Category_A_None
4,16805,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,Q1,2018,NaT,25,USD,13357192.50,USD,13357192.5,Closed Lost,Prod_Category_A_None
5,16802,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,Q1,2018,NaT,28,USD,14838277.50,USD,14838277.5,Closed Lost,Prod_Category_A_None
6,16799,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,Q1,2017,NaT,7,USD,2659494.60,USD,2659494.6,Closed Lost,Prod_Category_A_None
132,5581,Americas,NE America,1,1,1,1,0,Bureaucratic_Code_4,2015-12-18,...,Q2,2016,NaT,1,USD,629145.00,USD,0.0,Closed Lost,Prod_Category_A_None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16930,28372,Americas,SE America,1,0,1,0,0,Bureaucratic_Code_5,2015-09-25,...,Q2,2016,NaT,120,USD,76800640.00,USD,76800640.0,Closed Lost,Prod_Category_A_None
16940,20827,Americas,NE America,1,0,0,0,0,Bureaucratic_Code_5,2014-06-16,...,Q4,2016,NaT,20,USD,10751580.00,USD,21332500.0,Closed Lost,Prod_Category_A_None
16941,20830,Americas,NE America,1,0,0,0,0,Bureaucratic_Code_5,2014-06-16,...,Q4,2016,NaT,20,USD,10580920.00,USD,21332500.0,Closed Lost,Prod_Category_A_None
16945,28561,Americas,NE America,1,1,1,1,0,Bureaucratic_Code_4,2015-10-20,...,Q2,2016,NaT,4,USD,2346796.88,USD,0.0,Closed Lost,Prod_Category_A_None
16946,28318,Americas,NE America,1,1,1,1,0,Bureaucratic_Code_4,2015-09-03,...,Q3,2016,NaT,40,USD,25603200.00,USD,0.0,Closed Lost,Prod_Category_A_None

In [5]:
oportunidades_ganadas_Americas = data_frame[(data_frame.Stage == 'Closed Won') & (data_frame.Region == 'Americas')]
oportunidades_ganadas_Americas

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,...,Delivery_Quarter,Delivery_Year,Actual_Delivery_Date,TRF,Total_Amount_Currency,Total_Amount,Total_Taxable_Amount_Currency,Total_Taxable_Amount,Stage,Prod_Category_A
2,27446,Americas,NW America,0,0,0,0,0,Bureaucratic_Code_4,2015-04-21,...,Q1,2016,NaT,0,USD,83865.6,USD,83865.6,Closed Won,Prod_Category_A_None
7,27455,Americas,NW America,1,1,1,1,0,Bureaucratic_Code_4,2015-04-21,...,Q1,2016,NaT,0,USD,50688.0,USD,50688.0,Closed Won,Prod_Category_A_None
64,19342,Americas,NW America,0,0,0,0,0,Bureaucratic_Code_4,2013-08-22,...,Q1,2016,NaT,5,USD,3184974.0,USD,3184974.0,Closed Won,Prod_Category_A_None
209,7770,Americas,SE America,1,1,1,1,0,Bureaucratic_Code_4,2015-12-22,...,Q2,2016,NaT,0,USD,147646.8,USD,147646.8,Closed Won,Prod_Category_A_None
461,8925,Americas,None,0,0,0,0,0,Bureaucratic_Code_4,2016-01-21,...,Q1,2016,NaT,0,USD,187.6,USD,187.6,Closed Won,Prod_Category_A_None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16667,19449,Americas,NW America,1,0,0,0,0,Bureaucratic_Code_5,2013-08-22,...,Q1,2016,NaT,23,USD,15080039.0,USD,15080039.0,Closed Won,Prod_Category_A_None
16675,23376,Americas,NW America,1,1,1,1,0,Bureaucratic_Code_4,2013-07-27,...,Q2,2016,NaT,1,USD,485520.0,USD,485520.0,Closed Won,Prod_Category_A_None
16759,19426,Americas,NW America,1,0,0,0,0,Bureaucratic_Code_5,2013-08-22,...,Q1,2016,NaT,22,USD,14430065.0,USD,14430065.0,Closed Won,Prod_Category_A_None
16834,21013,Americas,NW America,0,0,0,0,0,Bureaucratic_Code_4,2013-07-27,...,Q1,2016,NaT,1,USD,891800.0,USD,0.0,Closed Won,Prod_Category_A_None
16864,27461,Americas,NW America,0,0,0,0,0,Bureaucratic_Code_4,2015-04-21,...,Q1,2016,NaT,0,USD,139160.0,USD,139160.0,Closed Won,Prod_Category_A_None