In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data_frame = pd.read_csv('Entrenamieto_ECI_2020.csv')
data_frame.Account_Created_Date = pd.to_datetime(data_frame.Account_Created_Date)
data_frame.Actual_Delivery_Date = pd.to_datetime(data_frame.Actual_Delivery_Date)
data_frame.Opportunity_Created_Date = pd.to_datetime(data_frame.Opportunity_Created_Date)
data_frame.Quote_Expiry_Date = pd.to_datetime(data_frame.Quote_Expiry_Date)
data_frame.Last_Modified_Date = pd.to_datetime(data_frame.Last_Modified_Date)
data_frame.Planned_Delivery_Start_Date = pd.to_datetime(data_frame.Planned_Delivery_Start_Date)
data_frame

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,...,Delivery_Quarter,Delivery_Year,Actual_Delivery_Date,TRF,Total_Amount_Currency,Total_Amount,Total_Taxable_Amount_Currency,Total_Taxable_Amount,Stage,Prod_Category_A
0,27761,EMEA,None,1,1,1,1,0,Bureaucratic_Code_4,2015-06-16,...,Q2,2016,NaT,10,EUR,5272800.00,EUR,5272800.0,Closed Lost,Prod_Category_A_None
1,27760,EMEA,None,0,0,0,0,0,Bureaucratic_Code_4,2015-06-16,...,Q1,2016,NaT,0,EUR,48230.00,EUR,48230.0,Closed Won,Prod_Category_A_None
2,27446,Americas,NW America,0,0,0,0,0,Bureaucratic_Code_4,2015-04-21,...,Q1,2016,NaT,0,USD,83865.60,USD,83865.6,Closed Won,Prod_Category_A_None
3,16808,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,Q1,2018,NaT,14,USD,7421881.50,USD,7421881.5,Closed Lost,Prod_Category_A_None
4,16805,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,Q1,2018,NaT,25,USD,13357192.50,USD,13357192.5,Closed Lost,Prod_Category_A_None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16942,8781,EMEA,Austria,1,1,1,1,0,Bureaucratic_Code_4,2016-01-15,...,Q1,2016,NaT,0,EUR,103350.00,EUR,299715.0,Closed Won,Prod_Category_A_None
16943,8786,EMEA,Austria,1,1,1,1,0,Bureaucratic_Code_4,2016-01-15,...,Q2,2016,NaT,0,EUR,93015.00,EUR,299715.0,Closed Won,Prod_Category_A_None
16944,8792,EMEA,Austria,1,1,1,1,0,Bureaucratic_Code_4,2016-01-15,...,Q1,2016,NaT,0,EUR,103350.00,EUR,299715.0,Closed Won,Prod_Category_A_None
16945,28561,Americas,NE America,1,1,1,1,0,Bureaucratic_Code_4,2015-10-20,...,Q2,2016,NaT,4,USD,2346796.88,USD,0.0,Closed Lost,Prod_Category_A_None
16946,28318,Americas,NE America,1,1,1,1,0,Bureaucratic_Code_4,2015-09-03,...,Q3,2016,NaT,40,USD,25603200.00,USD,0.0,Closed Lost,Prod_Category_A_None

In [3]:
oportunidades_ganadas_EMEA = data_frame[(data_frame.Stage == 'Closed Won') & (data_frame.Region == 'EMEA')]
oportunidades_ganadas_EMEA

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,...,Delivery_Quarter,Delivery_Year,Actual_Delivery_Date,TRF,Total_Amount_Currency,Total_Amount,Total_Taxable_Amount_Currency,Total_Taxable_Amount,Stage,Prod_Category_A
1,27760,EMEA,None,0,0,0,0,0,Bureaucratic_Code_4,2015-06-16,...,Q1,2016,NaT,0,EUR,48230.0,EUR,48230.00,Closed Won,Prod_Category_A_None
63,13392,EMEA,Germany,0,0,0,0,0,Bureaucratic_Code_4,2013-07-27,...,Q1,2016,NaT,0,EUR,103350.0,EUR,103350.00,Closed Won,Prod_Category_A_None
66,18491,EMEA,United Kingdom,0,0,0,0,0,Bureaucratic_Code_4,2014-01-08,...,Q1,2016,NaT,0,EUR,214500.0,EUR,214500.00,Closed Won,Prod_Category_A_None
67,18494,EMEA,United Kingdom,0,0,0,0,0,Bureaucratic_Code_4,2014-01-08,...,Q1,2016,NaT,0,EUR,214500.0,EUR,214500.00,Closed Won,Prod_Category_A_None
70,19680,EMEA,United Kingdom,0,0,0,0,0,Bureaucratic_Code_4,2013-07-27,...,Q1,2016,NaT,0,EUR,107250.0,EUR,420750.00,Closed Won,Prod_Category_A_None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16937,17683,EMEA,Germany,0,0,0,0,0,Bureaucratic_Code_4,2013-07-27,...,Q1,2016,NaT,1,EUR,413400.0,EUR,528918.75,Closed Won,Prod_Category_A_None
16939,18324,EMEA,Norway,1,1,0,0,0,Bureaucratic_Code_4,2013-07-27,...,Q2,2016,NaT,1,EUR,401700.0,EUR,401700.00,Closed Won,Prod_Category_A_None
16942,8781,EMEA,Austria,1,1,1,1,0,Bureaucratic_Code_4,2016-01-15,...,Q1,2016,NaT,0,EUR,103350.0,EUR,299715.00,Closed Won,Prod_Category_A_None
16943,8786,EMEA,Austria,1,1,1,1,0,Bureaucratic_Code_4,2016-01-15,...,Q2,2016,NaT,0,EUR,93015.0,EUR,299715.00,Closed Won,Prod_Category_A_None
16944,8792,EMEA,Austria,1,1,1,1,0,Bureaucratic_Code_4,2016-01-15,...,Q1,2016,NaT,0,EUR,103350.0,EUR,299715.00,Closed Won,Prod_Category_A_None

In [4]:
oportunidades_perdidas_EMEA = data_frame[(data_frame.Stage == 'Closed Lost') & (data_frame.Region == 'EMEA')]
oportunidades_perdidas_EMEA

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,...,Delivery_Quarter,Delivery_Year,Actual_Delivery_Date,TRF,Total_Amount_Currency,Total_Amount,Total_Taxable_Amount_Currency,Total_Taxable_Amount,Stage,Prod_Category_A
0,27761,EMEA,None,1,1,1,1,0,Bureaucratic_Code_4,2015-06-16,...,Q2,2016,NaT,10,EUR,5272800.00,EUR,5272800.00,Closed Lost,Prod_Category_A_None
62,18557,EMEA,Italy,1,1,1,1,0,Bureaucratic_Code_4,2013-07-27,...,Q2,2016,NaT,0,EUR,259875.00,EUR,259875.00,Closed Lost,Prod_Category_A_None
68,4920,EMEA,United Kingdom,1,1,0,0,0,Bureaucratic_Code_4,2015-12-10,...,Q1,2016,NaT,3,EUR,1556587.50,EUR,1556587.50,Closed Lost,Prod_Category_A_None
69,17590,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2013-07-27,...,Q2,2017,NaT,1,EUR,549780.00,EUR,549780.00,Closed Lost,Prod_Category_A_None
78,4904,EMEA,UAE (Dubai),1,0,1,0,0,Bureaucratic_Code_5,2015-12-08,...,Q2,2016,NaT,0,USD,7695.00,USD,7695.00,Closed Lost,Prod_Category_A_None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16857,14759,EMEA,Germany,0,0,0,0,0,Bureaucratic_Code_4,2013-07-27,...,Q1,2016,NaT,0,EUR,105300.00,EUR,105300.00,Closed Lost,Prod_Category_A_None
16928,19906,EMEA,France,0,0,0,0,0,Bureaucratic_Code_4,2013-07-27,...,Q4,2016,NaT,1,EUR,308261.25,EUR,308261.25,Closed Lost,Prod_Category_A_None
16929,12703,EMEA,France,1,1,1,1,0,Bureaucratic_Code_4,2013-07-27,...,Q4,2016,NaT,15,EUR,7651020.00,EUR,7651020.00,Closed Lost,Prod_Category_A_None
16932,15785,EMEA,Germany,0,0,0,0,0,Bureaucratic_Code_4,2013-07-27,...,Q1,2016,NaT,0,EUR,160650.00,EUR,160650.00,Closed Lost,Prod_Category_A_None
16938,28767,EMEA,Germany,1,0,0,0,0,Bureaucratic_Code_5,2015-12-04,...,Q3,2016,NaT,3,EUR,1307775.00,EUR,1307775.00,Closed Lost,Prod_Category_A_None

In [5]:
data_frame.dtypes

ID                                             int64
Region                                        object
Territory                                     object
Pricing, Delivery_Terms_Quote_Appr             int64
Pricing, Delivery_Terms_Approved               int64
Bureaucratic_Code_0_Approval                   int64
Bureaucratic_Code_0_Approved                   int64
Submitted_for_Approval                         int64
Bureaucratic_Code                             object
Account_Created_Date                  datetime64[ns]
Source                                        object
Billing_Country                               object
Account_Name                                  object
Opportunity_Name                              object
Opportunity_ID                                 int64
Sales_Contract_No                             object
Account_Owner                                 object
Opportunity_Owner                             object
Account_Type                                  object
Opportunity_Type                              object
Quote_Type                                    object
Delivery_Terms                                object
Opportunity_Created_Date              datetime64[ns]
Brand                                         object
Product_Type                                  object
Size                                          object
Product_Category_B                            object
Price                                         object
Currency                                      object
Last_Activity                                 object
Quote_Expiry_Date                     datetime64[ns]
Last_Modified_Date                    datetime64[ns]
Last_Modified_By                              object
Product_Family                                object
Product_Name                                  object
ASP_Currency                                  object
ASP                                          float64
ASP_(converted)_Currency                      object
ASP_(converted)                              float64
Planned_Delivery_Start_Date           datetime64[ns]
Planned_Delivery_End_Date                     object
Month                                         object
Delivery_Quarter                              object
Delivery_Year                                  int64
Actual_Delivery_Date                  datetime64[ns]
TRF                                            int64
Total_Amount_Currency                         object
Total_Amount                                 float64
Total_Taxable_Amount_Currency                 object
Total_Taxable_Amount                         float64
Stage                                         object
Prod_Category_A                               object
dtype: object

In [6]:
oportunidades_ganadas_EMEA.Billing_Country.value_counts()

Germany                                       1121
Netherlands                                    315
Spain                                          192
Italy                                          152
United Kingdom                                 127
Austria                                        122
Belgium                                        119
France                                         111
Luxembourg                                      89
Cyprus                                          34
Portugal                                        18
Poland                                          16
Turkey                                           7
Norway                                           7
Switzerland                                      6
Hungary                                          6
South Africa                                     5
Malta                                            5
Sweden                                           4
Jordan                                           4
Czech Republic                                   3
Reunion                                          2
United States                                    2
Bulgaria                                         1
Macedonia, the former Yugoslav Republic of       1
Estonia                                          1
United Arab Emirates                             1
Name: Billing_Country, dtype: int64

In [7]:
oportunidades_perdidas_EMEA.Billing_Country.value_counts()

Germany                                       832
France                                        282
Netherlands                                   248
United Kingdom                                152
Italy                                         141
Spain                                         123
Belgium                                       107
Luxembourg                                     47
Poland                                         36
Austria                                        23
United Arab Emirates                           20
Switzerland                                    20
Norway                                         15
Ireland                                        13
Cyprus                                         12
Turkey                                         10
Denmark                                        10
Portugal                                        9
Greece                                          9
French Southern Territories                     8
None                                            8
Czech Republic                                  7
Hungary                                         7
Brazil                                          5
Sweden                                          4
Singapore                                       4
United States                                   4
Macedonia, the former Yugoslav Republic of      3
South Africa                                    3
Bulgaria                                        3
Ghana                                           2
Mexico                                          2
Armenia                                         2
Slovakia                                        2
Egypt                                           2
Albania                                         2
Malta                                           2
Belarus                                         2
Bosnia and Herzegovina                          1
Peru                                            1
Liechtenstein                                   1
Estonia                                         1
China                                           1
Kenya                                           1
Saudi Arabia                                    1
Morocco                                         1
Name: Billing_Country, dtype: int64