In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data_frame = pd.read_csv('Entrenamieto_ECI_2020.csv')
data_frame.Account_Created_Date = pd.to_datetime(data_frame.Account_Created_Date)
data_frame.Actual_Delivery_Date = pd.to_datetime(data_frame.Actual_Delivery_Date)
data_frame.Opportunity_Created_Date = pd.to_datetime(data_frame.Opportunity_Created_Date)
data_frame.Quote_Expiry_Date = pd.to_datetime(data_frame.Quote_Expiry_Date)
data_frame.Last_Modified_Date = pd.to_datetime(data_frame.Last_Modified_Date)
data_frame.Planned_Delivery_Start_Date = pd.to_datetime(data_frame.Planned_Delivery_Start_Date)
data_frame

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,...,Delivery_Quarter,Delivery_Year,Actual_Delivery_Date,TRF,Total_Amount_Currency,Total_Amount,Total_Taxable_Amount_Currency,Total_Taxable_Amount,Stage,Prod_Category_A
0,27761,EMEA,None,1,1,1,1,0,Bureaucratic_Code_4,2015-06-16,...,Q2,2016,NaT,10,EUR,5272800.00,EUR,5272800.0,Closed Lost,Prod_Category_A_None
1,27760,EMEA,None,0,0,0,0,0,Bureaucratic_Code_4,2015-06-16,...,Q1,2016,NaT,0,EUR,48230.00,EUR,48230.0,Closed Won,Prod_Category_A_None
2,27446,Americas,NW America,0,0,0,0,0,Bureaucratic_Code_4,2015-04-21,...,Q1,2016,NaT,0,USD,83865.60,USD,83865.6,Closed Won,Prod_Category_A_None
3,16808,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,Q1,2018,NaT,14,USD,7421881.50,USD,7421881.5,Closed Lost,Prod_Category_A_None
4,16805,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,Q1,2018,NaT,25,USD,13357192.50,USD,13357192.5,Closed Lost,Prod_Category_A_None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16942,8781,EMEA,Austria,1,1,1,1,0,Bureaucratic_Code_4,2016-01-15,...,Q1,2016,NaT,0,EUR,103350.00,EUR,299715.0,Closed Won,Prod_Category_A_None
16943,8786,EMEA,Austria,1,1,1,1,0,Bureaucratic_Code_4,2016-01-15,...,Q2,2016,NaT,0,EUR,93015.00,EUR,299715.0,Closed Won,Prod_Category_A_None
16944,8792,EMEA,Austria,1,1,1,1,0,Bureaucratic_Code_4,2016-01-15,...,Q1,2016,NaT,0,EUR,103350.00,EUR,299715.0,Closed Won,Prod_Category_A_None
16945,28561,Americas,NE America,1,1,1,1,0,Bureaucratic_Code_4,2015-10-20,...,Q2,2016,NaT,4,USD,2346796.88,USD,0.0,Closed Lost,Prod_Category_A_None
16946,28318,Americas,NE America,1,1,1,1,0,Bureaucratic_Code_4,2015-09-03,...,Q3,2016,NaT,40,USD,25603200.00,USD,0.0,Closed Lost,Prod_Category_A_None

In [3]:
japon_cerrados_df =  data_frame[ ( ((data_frame.Stage == 'Closed Won') |  (data_frame.Stage == 'Closed Lost') )& (data_frame.Region == 'Japan'))]
japon_cerrados_df

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,...,Delivery_Quarter,Delivery_Year,Actual_Delivery_Date,TRF,Total_Amount_Currency,Total_Amount,Total_Taxable_Amount_Currency,Total_Taxable_Amount,Stage,Prod_Category_A
8,24353,Japan,None,1,0,0,0,0,Bureaucratic_Code_5,2015-04-20,...,Q1,2016,NaT,0,JPY,15600.0,JPY,470400.0,Closed Lost,Prod_Category_A_None
9,24355,Japan,None,1,0,0,0,0,Bureaucratic_Code_5,2015-04-20,...,Q1,2016,NaT,0,JPY,4400.0,JPY,470400.0,Closed Lost,Prod_Category_A_None
10,24356,Japan,None,1,0,0,0,0,Bureaucratic_Code_5,2015-04-20,...,Q1,2016,NaT,0,JPY,6200.0,JPY,470400.0,Closed Lost,Prod_Category_A_None
11,24357,Japan,None,1,0,0,0,0,Bureaucratic_Code_5,2015-04-20,...,Q1,2016,NaT,0,JPY,140000.0,JPY,470400.0,Closed Lost,Prod_Category_A_None
12,24358,Japan,None,1,0,0,0,0,Bureaucratic_Code_5,2015-04-20,...,Q1,2016,NaT,0,JPY,304200.0,JPY,470400.0,Closed Lost,Prod_Category_A_None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16922,18519,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,2013-07-28,...,Q1,2016,NaT,0,USD,13200.0,USD,6422400.6,Closed Won,Prod_Category_A_None
16923,27689,Japan,None,1,1,0,0,0,Bureaucratic_Code_4,2015-06-11,...,Q1,2016,NaT,0,JPY,12194000.0,JPY,12194000.0,Closed Won,Prod_Category_A_None
16924,27688,Japan,None,1,1,0,0,0,Bureaucratic_Code_4,2015-06-11,...,Q1,2016,NaT,0,JPY,11959500.0,JPY,11959500.0,Closed Won,Prod_Category_A_None
16925,19062,Japan,Japan,0,0,0,0,0,Bureaucratic_Code_4,2013-08-11,...,Q1,2016,NaT,0,JPY,17537000.0,JPY,17537000.0,Closed Won,Prod_Category_A_None
16926,19066,Japan,Japan,1,1,1,1,0,Bureaucratic_Code_4,2013-08-11,...,Q1,2016,NaT,0,JPY,13860000.0,JPY,13860000.0,Closed Won,Prod_Category_A_None

In [4]:
japon_cerrados_df.Account_Created_Date.dt.year.value_counts()

2015    3626
2013     772
2016     209
2014     139
2017      81
2018      42
Name: Account_Created_Date, dtype: int64

In [5]:
japon_cerrados_ganadas_df = data_frame[(data_frame.Stage == 'Closed Won') & (data_frame.Region == 'Japan')]
japon_cerrados_ganadas_df

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,...,Delivery_Quarter,Delivery_Year,Actual_Delivery_Date,TRF,Total_Amount_Currency,Total_Amount,Total_Taxable_Amount_Currency,Total_Taxable_Amount,Stage,Prod_Category_A
65,24444,Japan,None,1,1,0,0,0,Bureaucratic_Code_4,2015-04-20,...,Q1,2016,NaT,0,JPY,243360.0,JPY,243360.0,Closed Won,Prod_Category_A_None
139,23618,Japan,Japan,0,0,0,0,0,Bureaucratic_Code_4,2014-12-19,...,Q1,2016,NaT,0,JPY,12852000.0,JPY,12852000.0,Closed Won,Prod_Category_A_None
140,23619,Japan,Japan,0,0,0,0,0,Bureaucratic_Code_4,2014-12-19,...,Q1,2016,NaT,0,JPY,29478000.0,JPY,29478000.0,Closed Won,Prod_Category_A_None
141,23614,Japan,Japan,0,0,0,0,0,Bureaucratic_Code_4,2014-12-19,...,Q1,2016,NaT,0,JPY,33916530.0,JPY,33916530.0,Closed Won,Prod_Category_A_None
142,23617,Japan,Japan,0,0,0,0,0,Bureaucratic_Code_4,2014-12-19,...,Q1,2016,NaT,1,JPY,37454400.0,JPY,37454400.0,Closed Won,Prod_Category_A_None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16922,18519,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,2013-07-28,...,Q1,2016,NaT,0,USD,13200.0,USD,6422400.6,Closed Won,Prod_Category_A_None
16923,27689,Japan,None,1,1,0,0,0,Bureaucratic_Code_4,2015-06-11,...,Q1,2016,NaT,0,JPY,12194000.0,JPY,12194000.0,Closed Won,Prod_Category_A_None
16924,27688,Japan,None,1,1,0,0,0,Bureaucratic_Code_4,2015-06-11,...,Q1,2016,NaT,0,JPY,11959500.0,JPY,11959500.0,Closed Won,Prod_Category_A_None
16925,19062,Japan,Japan,0,0,0,0,0,Bureaucratic_Code_4,2013-08-11,...,Q1,2016,NaT,0,JPY,17537000.0,JPY,17537000.0,Closed Won,Prod_Category_A_None
16926,19066,Japan,Japan,1,1,1,1,0,Bureaucratic_Code_4,2013-08-11,...,Q1,2016,NaT,0,JPY,13860000.0,JPY,13860000.0,Closed Won,Prod_Category_A_None

In [6]:
japon_cerrados_perdidas_df = data_frame[(data_frame.Stage == 'Closed Lost') & (data_frame.Region == 'Japan')]
japon_cerrados_perdidas_df

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,...,Delivery_Quarter,Delivery_Year,Actual_Delivery_Date,TRF,Total_Amount_Currency,Total_Amount,Total_Taxable_Amount_Currency,Total_Taxable_Amount,Stage,Prod_Category_A
8,24353,Japan,None,1,0,0,0,0,Bureaucratic_Code_5,2015-04-20,...,Q1,2016,NaT,0,JPY,15600.0,JPY,470400.0,Closed Lost,Prod_Category_A_None
9,24355,Japan,None,1,0,0,0,0,Bureaucratic_Code_5,2015-04-20,...,Q1,2016,NaT,0,JPY,4400.0,JPY,470400.0,Closed Lost,Prod_Category_A_None
10,24356,Japan,None,1,0,0,0,0,Bureaucratic_Code_5,2015-04-20,...,Q1,2016,NaT,0,JPY,6200.0,JPY,470400.0,Closed Lost,Prod_Category_A_None
11,24357,Japan,None,1,0,0,0,0,Bureaucratic_Code_5,2015-04-20,...,Q1,2016,NaT,0,JPY,140000.0,JPY,470400.0,Closed Lost,Prod_Category_A_None
12,24358,Japan,None,1,0,0,0,0,Bureaucratic_Code_5,2015-04-20,...,Q1,2016,NaT,0,JPY,304200.0,JPY,470400.0,Closed Lost,Prod_Category_A_None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16898,24701,Japan,None,1,0,0,0,0,Bureaucratic_Code_5,2015-04-20,...,Q1,2016,NaT,0,JPY,4400.0,JPY,470400.0,Closed Lost,Prod_Category_A_None
16899,24702,Japan,None,1,0,0,0,0,Bureaucratic_Code_5,2015-04-20,...,Q1,2016,NaT,0,JPY,6200.0,JPY,470400.0,Closed Lost,Prod_Category_A_None
16900,24703,Japan,None,1,0,0,0,0,Bureaucratic_Code_5,2015-04-20,...,Q1,2016,NaT,0,JPY,140000.0,JPY,470400.0,Closed Lost,Prod_Category_A_None
16901,24704,Japan,None,1,0,0,0,0,Bureaucratic_Code_5,2015-04-20,...,Q1,2016,NaT,0,JPY,304200.0,JPY,470400.0,Closed Lost,Prod_Category_A_None
16914,23781,Japan,None,1,1,0,0,0,Bureaucratic_Code_4,2015-02-10,...,Q1,2016,NaT,0,JPY,14196000.0,JPY,14196000.0,Closed Lost,Prod_Category_A_None

In [7]:
japon_cerrados_ganadas_df.Opportunity_Created_Date.dt.year.value_counts().sort_index()

2015     136
2016     948
2017    1567
2018     672
Name: Opportunity_Created_Date, dtype: int64

In [8]:
casos_ganados_japon_2015 = japon_cerrados_ganadas_df[japon_cerrados_ganadas_df.Opportunity_Created_Date.dt.year == 2015].Opportunity_Created_Date.value_counts()
casos_ganados_japon_iniciados_2015_df = casos_ganados_japon_2013.to_frame()
casos_ganados_japon_iniciados_2015_df.columns = ['Cantidad de casos abiertos en la fecha']
casos_ganados_japon_iniciados_2015_df

NameError: name 'casos_ganados_japon_2013' is not defined

In [ ]:
casos_ganados_japon_iniciados_2015_df.plot(kind = 'bar', figsize =(16,8), rot =65, title = 'Cantidad de casos ganados abiertos en el 2013', color = (0.7, 0.2, 0.4, 0.6));
ax=plt.gca()
ax.set_ylabel('Cantidad de casos abiertos');
ax.set_xlabel('Fecha')

In [ ]:
japon_cerrados_perdidas_df.Delivery_Year.value_counts()

In [ ]:
casos_perdidos_japon_2015_df = japon_cerrados_perdidas_df[japon_cerrados_perdidas_df.Opportunity_Created_Date.dt.year == 2015]
casos_perdidos_japon_2015_df

In [ ]:
grafico_casos_perdidos_creados_2015_df = casos_perdidos_japon_2015_df.Opportunity_Created_Date.value_counts().to_frame()
grafico_casos_perdidos_creados_2015_df.columns=['Cantidad de casos abiertos en la fecha']
grafico_casos_perdidos_creados_2015_df

In [ ]:
grafico_casos_perdidos_creados_2015_df.plot(kind = 'bar', figsize =(16,8), rot =65, title = 'Cantidad de casos perdidos abiertos 2015', color = (0.7, 0.2, 0.4, 0.6));
ax=plt.gca()
ax.set_ylabel('Cantidad de casos abiertos');
ax.set_xlabel('Fecha')

In [ ]:
japon_solo_anios_y_oportunidades_cerradas = japon_cerrados_df[['Stage','Opportunity_Created_Date']]
anio_cuentas_creadas = japon_solo_anios_y_oportunidades_cerradas.Opportunity_Created_Date.dt.year
japon_solo_anios_y_oportunidades_cerradas.loc[:,'Opportunity_Created_Date'] = anio_cuentas_creadas
#japon_solo_anios_y_oportunidades_cerradas.columns = ['Stage', 'Anio_de_oportunidad_creada']
#japon_solo_anios_y_oportunidades_cerradas.set_index(japon_solo_anios_y_oportunidades_cerradas.Stage, drop = True, inplace = True)
japon_solo_anios_y_oportunidades_cerradas

In [ ]:
anio_cuentas_creadas.value_counts().sort_index()

In [ ]:
casos_2015 = japon_solo_anios_y_oportunidades_cerradas[japon_solo_anios_y_oportunidades_cerradas.Opportunity_Created_Date == 2015]
casos_2015 = casos_2015.Stage.value_counts().to_frame(name = 'Anio_2015')
casos_2016 = japon_solo_anios_y_oportunidades_cerradas[japon_solo_anios_y_oportunidades_cerradas.Opportunity_Created_Date == 2016]
casos_2016 = casos_2016.Stage.value_counts().to_frame(name = 'Anio_2016')
casos_2017 = japon_solo_anios_y_oportunidades_cerradas[japon_solo_anios_y_oportunidades_cerradas.Opportunity_Created_Date == 2017]
casos_2017 = casos_2017.Stage.value_counts().to_frame(name = 'Anio_2017')
casos_2018 = japon_solo_anios_y_oportunidades_cerradas[japon_solo_anios_y_oportunidades_cerradas.Opportunity_Created_Date == 2018]
casos_2018 = casos_2018.Stage.value_counts().to_frame(name = 'Anio_2018')
casos_2015[['Anio_2016','Anio_2017']] = [casos_2016.Anio_2016, casos_2017.Anio_2017]
casos_2015['Anio_2018']= casos_2018.Anio_2018
casos_cerrados_por_anios = casos_2015
casos_cerrados_por_anios

In [ ]:
casos_cerrados_por_anios.plot.pie( subplots = True, figsize=(25, 10))